# # Imatge base a partir de la qual crearem la nostra
FROM 
# Directori per defecte de treball
WORKDIR 
# Copia la carpeta app dins "." de contenidor, a on "." és el WORKDIR
COPY 
# Exposa el port 80 del contenidor  
EXPOSE 

